import * as opentype from 'opentype.js';
import { mkdir, writeFile, rm } from 'node:fs/promises';
import { join, extname } from 'node:path';
import { randomUUID } from 'node:crypto';
import { spawn } from 'node:child_process';

const basePath = process.cwd();
const PORT = 3000;

// Path to Blender (adjust if needed)
const BLENDER = '/usr/sbin/blender';

// Coins generated by Blender are written here, then served once and cleaned up
const COIN_TMP = join(basePath, '.cointmp');

function tmpDir() {
    return join(COIN_TMP, randomUUID());
}

Bun.serve({
    port: PORT,
    async fetch(req) {
        const url = new URL(req.url);

        // POST /extract — Parse font file and export each glyph as SVG
        if (url.pathname === "/extract" && req.method === "POST") {
            try {
                const formData = await req.formData();
                const fontFile = formData.get('font');

                if (!fontFile || !(fontFile instanceof File)) {
                    return Response.json({ success: false, error: 'No font file uploaded' }, { status: 400 });
                }

                const buffer = await fontFile.arrayBuffer();
                let font;
                try {
                    font = opentype.parse(buffer);
                } catch (e) {
                    return Response.json({ success: false, error: 'Failed to parse font: ' + e.message }, { status: 400 });
                }

                const fontName = fontFile.name.replace(/\.[^/.]+$/, '').replace(/\s+/g, '');
                const folderName = `${fontName}Glyphs`;
                const outputDir = join(basePath, 'input', folderName);
                await mkdir(outputDir, { recursive: true });

                let count = 0;
                for (let i = 0; i < font.glyphs.length; i++) {
                    const glyph = font.glyphs.get(i);

                    let fileName;
                    if (glyph.unicode !== undefined) {
                        fileName = glyph.unicode.toString(16).toUpperCase().padStart(4, '0');
                    } else if (glyph.name) {
                        fileName = glyph.name;
                    } else {
                        fileName = `glyph_${i}`;
                    }

                    const ascender = font.ascender ?? 0;
                    const descender = font.descender ?? 0;
                    const unitsPerEm = font.unitsPerEm ?? 1000;

                    const path = glyph.getPath(0, ascender, unitsPerEm);
                    const svgPathData = path.toSVG(2);

                    const width = glyph.advanceWidth ?? unitsPerEm;
                    const height = ascender - descender;

                    const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}">
    ${svgPathData}
</svg>`;

                    await writeFile(join(outputDir, `${fileName}.svg`), svg);
                    count++;
                }

                return Response.json({
                    success: true,
                    count,
                    path: `input/${folderName}/`
                });
            } catch (error) {
                console.error(error);
                return Response.json({ success: false, error: error.message }, { status: 500 });
            }
        }

        if (url.pathname === "/generate-coin" && req.method === "POST") {
            try {
                const formData = await req.formData();
                const frontFile = formData.get('front');
                const backFile = formData.get('back');
                if (!frontFile || !backFile) {
                    return Response.json({ success: false, error: 'Missing front/back images' }, { status: 400 });
                }

                const width = parseFloat(formData.get('width')) || 2;
                const height = parseFloat(formData.get('height')) || 2;
                const depth = parseFloat(formData.get('depth')) || 0.16;

                const dir = tmpDir();
                await mkdir(dir, { recursive: true });

                const frontPath = join(dir, 'front' + (extname(frontFile.name) || '.png'));
                const backPath = join(dir, 'back' + (extname(backFile.name) || '.png'));
                const outPath = join(dir, 'coin.glb');
                const scriptPath = join(basePath, 'scripts', 'coin_from_images.py');

                // Write uploaded images to disk
                await writeFile(frontPath, Buffer.from(await frontFile.arrayBuffer()));
                await writeFile(backPath, Buffer.from(await backFile.arrayBuffer()));

                console.log(`Spawning Blender for coin (${width}×${height}×${depth}) …`);

                const result = await new Promise((resolve, reject) => {
                    const proc = spawn(BLENDER, [
                        '--background',
                        '--python', scriptPath,
                        '--',
                        '--front', frontPath,
                        '--back', backPath,
                        '--output', outPath,
                        '--width', String(width),
                        '--height', String(height),
                        '--depth', String(depth),
                    ], {
                        stdio: ['ignore', 'pipe', 'pipe'],
                    });

                    let stdout = '', stderr = '';
                    proc.stdout.on('data', d => stdout += d);
                    proc.stderr.on('data', d => stderr += d);

                    proc.on('close', code => {
                        console.log(`Blender exited with code ${code}`);
                        if (code === 0) resolve({ stdout, stderr });
                        else reject(new Error(`Blender exited with code ${code}\n${stderr}`));
                    });
                    proc.on('error', reject);
                });

                console.log('Blender output:\n', result.stdout);

                // Read the generated GLB
                const file = Bun.file(outPath);
                if (!(await file.exists())) {
                    throw new Error('GLB was not created by Blender');
                }

                const body = await file.bytes();

                // Clean up temp dir (async, don't block response)
                rm(dir, { recursive: true, force: true }).catch(() => {});

                return new Response(body, {
                    headers: {
                        'Content-Type': 'model/gltf-binary',
                        'Content-Disposition': 'attachment; filename="coin.glb"',
                    },
                });
            } catch (error) {
                console.error(error);
                return Response.json({ success: false, error: error.message }, { status: 500 });
            }
        }

    // Serve default input files
    if (url.pathname.startsWith("/input/")) {
        const inputPath = basePath + url.pathname;
        const inputFile = Bun.file(inputPath);
        if (await inputFile.exists()) {
            return new Response(inputFile);
        }
    }

    let filePath = basePath + url.pathname;
    if (url.pathname === "/") {
        filePath = basePath + "/index.html";
    }

    const file = Bun.file(filePath);
    if (await file.exists()) {
        return new Response(file);
    }

    return new Response("Not Found", { status: 404 });
    },
});

console.log(`Server running at http://localhost:${PORT}`);

// Automatically open the preview window in the browser
try {
    Bun.spawn(["xdg-open", `http://localhost:${PORT}`]);
    console.log("Opening preview window in the browser...");
} catch (e) {
    console.error("Could not automatically open browser.");
}
